import Logo from './logo/logo2.svg'
import BackgroundLogin from './background/background-login.png'
import Email from './Vector.svg'
import IconBook from './icons/icon-book.svg'
import IconActionEdit from './icons/bx_edit.svg'
import IconDelete from './icons/icon-delete.svg'
import ImageFirst from './image_1.svg'
import ImageSecond from './image_2.svg'
import Facebook from './icons/facebook.svg'
import Twitter from './icons/twetter.svg'
import Instagram from './icons/instagram.svg'
import Linkedin from './icons/linkedin.svg'
import LogoBni from './logo/logoBni.svg'
import QrImage from './qrImage.svg'
export { Logo, BackgroundLogin, Email, IconBook, IconActionEdit, IconDelete, ImageFirst, ImageSecond, Facebook, Twitter, Instagram, Linkedin, LogoBni, QrImage }